const usernames = [
  'Aaran1',
  'Aaren2',
  'Aarez3',
  'Aarman4',
  'Aaron5',
  'Aaron-James6',
  'Aarron7',
  'Aaryan8',
  'Aaryn9',
  'Aayan10',
  'Aazaan11',
  'Abaan12',
  'Abbas13',
  'Abdallah14',
  'Abdalroof15',
  'Abdihakim16',
  'Abdirahman17',
  'Abdisalam18',
  'Abdul19',
  'Abdul-Aziz20',
  'Abdulbasir21',
  'Abdulkadir22',
  'Abdulkarem23',
  'Smith24',
  'Jones25',
  'Hailey26',
  'Louis27',
  'Ani28',
  'Sunny29',
  'Tristan30',
  'Isaiah31',
  'Clare32',
  'Benjamin33',
  'Jamie34',
  'Ingrid35',
  'Jordan36',
  'Nina37',
  'Madelyn38',
  'Taylor39',
  'Ze40',
  'Zechariah41',
  'Zeek42',
  'Zeeshan43',
  'Zeid44',
  'Zein45',
  'Zen46',
  'Zendel47',
  'Zenith48',
  'Zennon49',
  'Zeph50',
  'Zerah51',
  'Zhen52',
  'Zhi53',
  'Zhong54',
  'Zhuo55',
  'Zi56',
  'Zidane57',
  'Zijie58',
  'Zinedine59',
  'Zion60',
  'Zishan61',
  'Ziya62',
  'Ziyaan63',
  'Zohaib64',
  'Zohair65',
  'Zoubaeir66',
  'Zubair67',
  'Zubayr68',
  'Zuriel69',
  'Xander70',
  'Jared71',
  'Courtney72',
  'Gillian73',
  'Clark74',
  'Jared75',
  'Grace76',
  'Kelsey77',
  'Tamar78',
  'Mark79',
  'Tamar80',
  'Farish81',
  'Sarah82',
  'Nathaniel83',
  'Parker84',
];

const reactions = [
  "👍",
  "👎",
  "❤️",
  "😂",
  "😢",
  "😡",
  "🤔",
  "🎉",
  "🙌",
  "🤷",
  "💩",
];

const thoughts = [
  'American flags left on the moon will eventually get bleached white by the sun.',
  'While they are hibernating, bears do not urinate. Their bodies convert waste into protein.',
  'White-faced capuchin monkeys greet each other by sticking their fingers up each others’ noses.',
  'Gummy bears were originally called "dancing bears."',
  'New Zealand has more cats per person than any other country in the world.',
  'The hagfish is the only animal that has a skull but no spine.',
  'People weigh less if they stand at the equator than if they stand at the North or South poles.',
  'The yo-yo was originally a weapon used in the Philippine jungle.',
  'Victor Hugo’s novel Les Miserable contains a sentence that is 823 words long.',
  'Alexander the Great was the first person to be pictured on a coin.',
  'FDR’s portrait was on the dime because of his association with the March of Dimes charity.',
  'The sun weighs 2,000 million million million million tons.',
  'Shoes that were specific to left and right were not made until the Civil War.',
  'The Turks call the turkey an “American bird.”',
  'Lightning kills about 10,000 people a year worldwide, more people than tornadoes or flooding.',
  'At an average of 15 breaths per minute, we take about 400 million breaths during a lifetime. This is equivalent to about 53 million gallons of air.',
  'The shiniest living thing on earth is the Pollia Condensata, an African fruit.',
  'The bee hummingbird drinks from up to 1,500 flowers a day.',
  'We throw away enough ribbon each year to tie a bow around the entire Earth.',
  'Comets in ancient Greece were called “hairy stars.”',
  'African lions catch about 20% of the prey they chase. Dragonflies catch 95%.',
  'A “cronut” is a cross between a doughnut and a croissant.',
  'Amazon.com was originally called a cadabra.',
  'A human loses about a million skin cells per 24 hours.',
  'Rabbits can see behind them without moving their heads.',
  'Even though the blue whale is the largest animal on earth, it can’t swallow anything bigger than a beach ball.',
  'Every year, about 100 billion servings of instant ramen are sold each year, or about 14 bowls per person.',
  'Mistletoe has no scent.',
  'A Chihuahua and a dachshund mix is a “chiweenie.”',
  'The Hungarian word for "quotation marks" is "macskaköröm," which literally translates to "cat claws."',
  'There are no seagulls in Hawaii.',
  'The sound of Darth Vader’s difficult breathing was made with a scuba regulator.',
  'Luke Skywaker was originally named Luke Skykiller.',
  'A moonbow is a rainbow produced by moonlight rather than direct sunlight.',
  'The # symbol isn’t officially called a hashtag or a pound. It’s technically called an "octothorpe." The “octo-” means “eight” to refer to its points.',
  '"Respair" is a 15th-century word meaning ‘fresh hope’ or a recovery from despair.',
  'A group of stingrays is called a fever.',
  'The plural of cul-de-sac is culs-de-sac.',
  'The term "lawn mullet" means having a neatly manicured front yard and an unmowed mess in the back.',
  'Raccoons have four times more sensory cells in their paws than most mammals. This allows them to "see" with their hands and get images of the object they touch without even looking at them.',
  'Being compassionate to others--as well as oneself--leads to greater happiness.',
  'Snow-bones are the lines of snow or ice left at the sides of roads after the rest of the snow has melted.',
  'Toxic people undermine, discourage, sabotage, and take advantage of you. "Nutric" people do the opposite, which is why it is so important to surround yourself with them.',
];

// Gets a random username
const getArrayOfNames = () => {
  return nameArr;
};

// Gets array of messages
const getMessages = () => {
  return messages;
};

// Gets a random reaction
const getReaction = () => {
  return reactions[Math.floor(Math.random() * reactions.length)];
};

// Export the functions for use in seed.js
module.exports = { getArrayOfNames, getMessages, getReaction };
